plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\桌面\\AI 生成文件\\ai-copywriter\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "pnpm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]